defaults: &defaults
  host: localhost
  autosave: true
  identity_map_enabled: true
  include_root_in_json: false
  persist_in_safe_mode: true
  allow_dynamic_fields: false

development: &development
  <<: *defaults
  autocreate_indexes: true
  max_retries_on_connection_failure: 6
  logger: true
  database: poc_api_app_development

test:
  <<: *defaults
  host: localhost
  database: poc_api_app_test

# set these environment variables on your prod server
production:
  <<: *defaults
  logger: true
  database: poc_api_app
  max_retries_on_connection_failure: 2
  autocreate_indexes: true
